//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cms_Group()
        {
            this.cms_Student = new HashSet<cms_Student>();
        }
    
        public int GroupId { get; set; }
        public string Leader { get; set; }
        public int ClassId { get; set; }
    
        public virtual cms_Class cms_Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_Student> cms_Student { get; set; }
    }
}
