//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_Student
    {
        public int StudentId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Facebook { get; set; }
        public int ClassId { get; set; }
        public int GroupId { get; set; }
    
        public virtual cms_Class cms_Class { get; set; }
        public virtual cms_Group cms_Group { get; set; }
    }
}
